
server:
    port:8721
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8721/eureka/
spring:
  application:
    name: microservice
security:
  user:
    name: chen
    password: 123456
